### ISSUE TITLE
Not downloading the right amount of images

### ISSUE THREAD

**Issue by LilChickenz** [nobodyme/reddit-fetch#3]
I initially tried to download 1000 images from r/EarthPorn and it only gave me 90. Tried again with 20 and it gave me 17, and it gave me 4 when i put 5. Why isn't it giving all of them?

**Comment by nobodyme** [comment]
Hi @LilChickenz, yes, sometimes you do get less images than you give because at times the post exists but the images are deleted, but after your request I guess it would be better to skip those deleted images to move on to the next to get the count you wanted. I will change the way that works.

As for 1000 images returning 90, reddit returns only 100 in the first page. Will try to improve that to fetch the consecutive pages or limit the max to 100 depending upon the time I have at hand. Thank you.

**Comment by nobodyme** [comment]
The tool must give you the exact no of images requested now.
